export const ROUTES = {
    HOME: 'HOME',
    HOME_TAB: 'Home',
    SPLASH: 'SPLASH',
    LOGIN: 'LOGIN',
    ME_TAB: 'Me',
    ONBOARDING: 'ONBOARDING',
    EDIT_INFORMATION: 'EDIT_INFOMATION',
    LIST_VIDEO: 'LIST_VIDEO',
    STEP: 'STEP',
    SLEEPTRACKING: 'SLEEPTRACKING',
    HEART: 'HEART',
    WEATHER: 'WEATHER_SCREEN',
    GOALS_SCREEN: 'GOALS_SCREEN',
    SETTINGS_SCREEN: 'SETTINGS_SCREEN',
    CHANGE_GOALS_SCREEN: 'CHANGE_GOALS_SCREEN',
    TRAINING_SCHEDULE: 'TRAINING_SCHEDULE',
    SPORT_TAB: 'Sport',
    SPORT: 'Sport',
    RUNNINGOUTDOOR: 'RunningOutDoor',
    DETAILS: 'Details',

    BloodPresssure: 'BloodPresssure',
    BloodPressurePost1: 'BloodPressurePost1',
    BloodPressurePost2: 'BloodPressurePost2',
    BloodPressurePost3: 'BloodPressurePost3',
    BloodPressurePost4: 'BloodPressurePost4',
    BloodPressurePost5: 'BloodPressurePost5',

    BloodSugar: 'BloodSugar',
    BloodSugarPost1: 'BloodSugarPost1',
    BloodSugarPost2: 'BloodSugarPost2',
    BloodSugarPost3: 'BloodSugarPost3',
    BloodSugarPost4: 'BloodSugarPost4',
    BloodSugarPost5: 'BloodSugarPost5',

    BodyWeight: 'BodyWeight',
    BodyWeightPost1: 'BodyWeightPost1',
    BodyWeightPost2: 'BodyWeightPost2',
    BodyWeightPost3: 'BodyWeightPost3',
    BodyWeightPost4: 'BodyWeightPost4',
    BodyWeightPost5: 'BodyWeightPost5',

    HealthyFood: 'HealthyFood',
    HealthyFoodPost1: 'HealthyFoodPost1',
    HealthyFoodPost2: 'HealthyFoodPost2',
    HealthyFoodPost3: 'HealthyFoodPost3',
    HealthyFoodPost4: 'HealthyFoodPost4',
    HealthyFoodPost5: 'HealthyFoodPost5',

    VIEWSETTING: 'ViewSetting',
    Waittime: 'Waittime',
    TermAndCondition: "TermAndCondition",
    HelpAndSupport: "HelpAndSupport",
    MotionSetting: "MotionSetting",
    SetTarget: "SetTarget",
    Walking: 'Walking',
    History: "History"
}